import { MigrationInterface, QueryRunner } from "typeorm";

export class CreaTablaRestaurant1764128243224 implements MigrationInterface {
    name = 'CreaTablaRestaurant1764128243224'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "roles" ("id" BIGSERIAL NOT NULL, "nombre" character varying(50) NOT NULL, "descripcion" character varying(150), CONSTRAINT "UQ_a5be7aa67e759e347b1c6464e10" UNIQUE ("nombre"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mesas_estado_enum" AS ENUM('DISPONIBLE', 'OCUPADO', 'RESERVADO')`);
        await queryRunner.query(`CREATE TABLE "mesas" ("id" BIGSERIAL NOT NULL, "sede_id" bigint, "numero_mesa" integer NOT NULL, "capacidad" integer NOT NULL DEFAULT '4', "estado" "public"."mesas_estado_enum" NOT NULL DEFAULT 'DISPONIBLE', CONSTRAINT "PK_ccff054bd3dad6539869d03350c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "aperturas_caja" ("id" BIGSERIAL NOT NULL, "caja_id" bigint, "usuario_apertura_id" bigint NOT NULL, "usuario_cierre_id" bigint, "fecha_apertura" TIMESTAMP, "fecha_cierre" TIMESTAMP, "monto_apertura" numeric(10,2) NOT NULL DEFAULT '0', "monto_cierre" numeric(10,2), "observaciones" text, CONSTRAINT "PK_5d6e6a98f354f4c5deecb8641f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."clientes_tipo_documento_enum" AS ENUM('DNI', 'RUC')`);
        await queryRunner.query(`CREATE TABLE "clientes" ("id" BIGSERIAL NOT NULL, "tipo_documento" "public"."clientes_tipo_documento_enum" NOT NULL DEFAULT 'DNI', "numero_documento" character varying(20) NOT NULL, "razon_social" character varying(150) NOT NULL, "direccion" character varying(200), "email" character varying(100), "telefono" character varying(20), CONSTRAINT "UQ_bcc2e579b8dd6243989d6f20400" UNIQUE ("numero_documento"), CONSTRAINT "PK_d76bf3571d906e4e86470482c08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categorias" ("id" BIGSERIAL NOT NULL, "nombre" text NOT NULL, "descripcion" text, CONSTRAINT "PK_3886a26251605c571c6b4f861fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalle_pedidos" ("id" BIGSERIAL NOT NULL, "pedido_id" bigint NOT NULL, "producto_id" bigint NOT NULL, "cantidad" integer NOT NULL, "precio_unitario" numeric(10,2) NOT NULL, "subtotal" numeric(10,2) NOT NULL, "tiempo_inicio_prep" TIMESTAMP, "tiempo_fin_prep" TIMESTAMP, CONSTRAINT "PK_89574e815e366720ce00fd1b31f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalle_facturas_proveedores" ("id" BIGSERIAL NOT NULL, "factura_id" bigint NOT NULL, "producto_detectado" character varying(150), "cantidad_detectada" integer NOT NULL DEFAULT '0', "precio_unitario" numeric(10,2) NOT NULL DEFAULT '0', "producto_id" bigint, "confianza_ia" numeric(5,4), "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_832303f5eaf38628c108b663fd5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."facturas_proveedores_procesado_por_ia_enum" AS ENUM('SI', 'NO')`);
        await queryRunner.query(`CREATE TYPE "public"."facturas_proveedores_estado_enum" AS ENUM('PENDIENTE', 'PROCESADO', 'ERROR')`);
        await queryRunner.query(`CREATE TABLE "facturas_proveedores" ("id" BIGSERIAL NOT NULL, "proveedor" character varying(150) NOT NULL, "numero_factura" character varying(50) NOT NULL, "fecha_emision" date, "total" numeric(10,2), "ruta_archivo" character varying(255), "procesado_por_ia" "public"."facturas_proveedores_procesado_por_ia_enum" NOT NULL DEFAULT 'NO', "modelo_ia_id" bigint, "fecha_procesamiento" TIMESTAMP, "estado" "public"."facturas_proveedores_estado_enum" NOT NULL DEFAULT 'PENDIENTE', "observaciones" text, CONSTRAINT "PK_0eaee1c77641558d359b9b45abc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."modelo_ia_tipo_enum" AS ENUM('DEMANDA', 'RECOMENDACION', 'INVENTARIO', 'CHATBOT', 'FACTURA_OCR')`);
        await queryRunner.query(`CREATE TYPE "public"."modelo_ia_estado_enum" AS ENUM('ACTIVO', 'INACTIVO', 'OBSOLETO')`);
        await queryRunner.query(`CREATE TABLE "modelo_ia" ("id" BIGSERIAL NOT NULL, "nombre" character varying(150) NOT NULL, "tipo" "public"."modelo_ia_tipo_enum" NOT NULL, "version" character varying(20) NOT NULL, "fecha_entrenamiento" TIMESTAMP NOT NULL DEFAULT now(), "precision_metrica" numeric(5,4), "ruta_artefacto" character varying(255), "estado" "public"."modelo_ia_estado_enum" NOT NULL DEFAULT 'ACTIVO', CONSTRAINT "PK_071425dfa5dd00bd46797dd4414" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."predicciones_demanda_hora_rango_enum" AS ENUM('MANANA', 'MEDIODIA', 'TARDE', 'NOCHE', 'DIA_COMPLETO')`);
        await queryRunner.query(`CREATE TABLE "predicciones_demanda" ("id" BIGSERIAL NOT NULL, "modelo_id" bigint NOT NULL, "fecha_prediccion" date NOT NULL, "hora_rango" "public"."predicciones_demanda_hora_rango_enum" NOT NULL, "producto_id" bigint, "cantidad_predicha" integer NOT NULL, "cantidad_real" integer, "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uk_prediccion_unica" UNIQUE ("fecha_prediccion", "hora_rango", "producto_id"), CONSTRAINT "PK_4a5cd40217b18149e503fb47316" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."productos_estado_enum" AS ENUM('ACTIVO', 'INACTIVO', 'OBSOLETO')`);
        await queryRunner.query(`CREATE TYPE "public"."productos_origen_enum" AS ENUM('MANUAL', 'IA')`);
        await queryRunner.query(`CREATE TABLE "productos" ("id" BIGSERIAL NOT NULL, "categoria_id" bigint, "nombre" character varying(100) NOT NULL, "descripcion" text, "precio" numeric(10,2) NOT NULL, "codigo_barras" character varying(50), "costo_produccion" numeric(10,2), "stock" integer NOT NULL DEFAULT '0', "estado" "public"."productos_estado_enum" NOT NULL DEFAULT 'ACTIVO', "origen" "public"."productos_origen_enum" NOT NULL DEFAULT 'MANUAL', "fecha_actualizacion" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_04f604609a0949a7f3b43400766" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "detalle_comprobantes" ("id" BIGSERIAL NOT NULL, "comprobante_id" bigint NOT NULL, "producto_id" bigint NOT NULL, "cantidad" integer, "precio_unitario" numeric(10,2), "total" numeric(10,2), CONSTRAINT "PK_5ffe191fe8073ebbd8441468f6d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."comprobantes_tipo_comprobante_enum" AS ENUM('BOLETA', 'FACTURA')`);
        await queryRunner.query(`CREATE TYPE "public"."comprobantes_estado_enum" AS ENUM('EMITIDO', 'PENDIENTE', 'ANULADO')`);
        await queryRunner.query(`CREATE TABLE "comprobantes" ("id" BIGSERIAL NOT NULL, "tipo_comprobante" "public"."comprobantes_tipo_comprobante_enum" NOT NULL DEFAULT 'BOLETA', "serie" character varying(10) NOT NULL, "numero" integer NOT NULL, "fecha_emision" TIMESTAMP NOT NULL DEFAULT now(), "cliente_id" bigint, "pedido_id" bigint NOT NULL, "caja_id" bigint NOT NULL, "subtotal" numeric(10,2), "igv" numeric(10,2), "total" numeric(10,2), "estado" "public"."comprobantes_estado_enum" NOT NULL DEFAULT 'PENDIENTE', "xml_hash" character varying(200), "cdr_respuesta" text, "ticket_sunat" character varying(50), "pdf_url" character varying(255), "xml_url" character varying(255), CONSTRAINT "PK_0c3ac75b725717ec0f082ece89b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."cajas_estado_enum" AS ENUM('ACTIVA', 'INACTIVA')`);
        await queryRunner.query(`CREATE TABLE "cajas" ("id" BIGSERIAL NOT NULL, "sede_id" bigint, "nombre" text NOT NULL, "ubicacion" text, "estado" "public"."cajas_estado_enum" NOT NULL DEFAULT 'INACTIVA', "user_id" bigint, "saldo_inicial" numeric(10,2) NOT NULL DEFAULT '0', "saldo_final" numeric(10,2) NOT NULL DEFAULT '0', "fecha_apertura" TIMESTAMP, "fecha_cierre" TIMESTAMP, "usuario_id" bigint, CONSTRAINT "PK_92b27e5f4ab36a544f37bf45e09" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."sedes_estado_enum" AS ENUM('active', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "sedes" ("id" BIGSERIAL NOT NULL, "nombre" character varying(150) NOT NULL, "direccion" character varying(255), "telefono" character varying(20), "ciudad" character varying(100), "estado" "public"."sedes_estado_enum" NOT NULL DEFAULT 'active', "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_518e95904db7c26167b8c719862" UNIQUE ("nombre"), CONSTRAINT "PK_842a6b0ebcf810b57487748b822" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_estado_enum" AS ENUM('ACTIVO', 'INACTIVO')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" BIGSERIAL NOT NULL, "nombre" character varying(100) NOT NULL, "apellido" character varying(100), "email" character varying(100) NOT NULL, "password" character varying(255) NOT NULL, "rol_id" bigint, "sede_id" bigint, "estado" "public"."users_estado_enum" NOT NULL DEFAULT 'ACTIVO', "fecha_registro" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."pedidos_estado_enum" AS ENUM('pendiente', 'preparacion', 'entregado', 'cancelado', 'pagado')`);
        await queryRunner.query(`CREATE TABLE "pedidos" ("id" BIGSERIAL NOT NULL, "mesa_id" bigint, "usuario_id" bigint NOT NULL, "cliente_id" bigint, "fecha" TIMESTAMP NOT NULL DEFAULT now(), "estado" "public"."pedidos_estado_enum" NOT NULL DEFAULT 'pendiente', "total" numeric(10,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_ebb5680ed29a24efdc586846725" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."ventas_metodo_pago_enum" AS ENUM('EFECTIVO', 'TARJETA', 'YAPE', 'PLIN', 'TRANSFERENCIA')`);
        await queryRunner.query(`CREATE TABLE "ventas" ("id" BIGSERIAL NOT NULL, "pedido_id" bigint NOT NULL, "comprobante_id" bigint NOT NULL, "caja_id" bigint NOT NULL, "metodo_pago" "public"."ventas_metodo_pago_enum" NOT NULL DEFAULT 'EFECTIVO', "monto_pagado" numeric(10,2), "vuelto" numeric(10,2) NOT NULL DEFAULT '0', "fecha_pago" TIMESTAMP NOT NULL DEFAULT now(), "usuario_id" bigint NOT NULL, CONSTRAINT "PK_b8b73abe8561829c019531d9a2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "mesas" ADD CONSTRAINT "FK_4ae856e133b757170844b0600f1" FOREIGN KEY ("sede_id") REFERENCES "sedes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" ADD CONSTRAINT "FK_65ef2d17b6bdf57e8d3be96f84f" FOREIGN KEY ("caja_id") REFERENCES "cajas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" ADD CONSTRAINT "FK_ecae228362b00d658c9e489cb56" FOREIGN KEY ("usuario_apertura_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" ADD CONSTRAINT "FK_5126a73f7a1f343a37907d9eca7" FOREIGN KEY ("usuario_cierre_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_pedidos" ADD CONSTRAINT "FK_2720cdda307d262cfe40a2fce30" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_pedidos" ADD CONSTRAINT "FK_095863249e22548b6cd85dae392" FOREIGN KEY ("producto_id") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_facturas_proveedores" ADD CONSTRAINT "FK_8647aa38fa76368ef98e78c1cf8" FOREIGN KEY ("factura_id") REFERENCES "facturas_proveedores"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_facturas_proveedores" ADD CONSTRAINT "FK_70bf44521a938647bcb03662af7" FOREIGN KEY ("producto_id") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facturas_proveedores" ADD CONSTRAINT "FK_16241fcacd3ab133d9a07abbfc4" FOREIGN KEY ("modelo_ia_id") REFERENCES "modelo_ia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predicciones_demanda" ADD CONSTRAINT "FK_8aa30ebfbdd26c5096fff5fff4c" FOREIGN KEY ("modelo_id") REFERENCES "modelo_ia"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "predicciones_demanda" ADD CONSTRAINT "FK_20a62f3a5ad61372f7b770c136a" FOREIGN KEY ("producto_id") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "productos" ADD CONSTRAINT "FK_5aaee6054b643e7c778477193a3" FOREIGN KEY ("categoria_id") REFERENCES "categorias"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_comprobantes" ADD CONSTRAINT "FK_ca7830e72f5b176b12ecee07f35" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "detalle_comprobantes" ADD CONSTRAINT "FK_1f8632e49bb51f6a35a52815fe7" FOREIGN KEY ("producto_id") REFERENCES "productos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_52efe547ddd86fa9592a8ab3dfe" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_5b52af61814a34be3ab6c162165" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "comprobantes" ADD CONSTRAINT "FK_2784134d13bb90b049a95b54274" FOREIGN KEY ("caja_id") REFERENCES "cajas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cajas" ADD CONSTRAINT "FK_64f074ffa88f2ad899dc9b1448d" FOREIGN KEY ("sede_id") REFERENCES "sedes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cajas" ADD CONSTRAINT "FK_6f28154a3dda0d70c72867f7c97" FOREIGN KEY ("usuario_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_685cb01ac5c88b5abb6bbe8aa60" FOREIGN KEY ("rol_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_51836035a0f08079451d537b245" FOREIGN KEY ("sede_id") REFERENCES "sedes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_ed48ccf11914571bc1c845e592d" FOREIGN KEY ("mesa_id") REFERENCES "mesas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_44db92bd8242455d454c1d2c5d9" FOREIGN KEY ("usuario_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pedidos" ADD CONSTRAINT "FK_2fc639de84f845569ac2c9f78aa" FOREIGN KEY ("cliente_id") REFERENCES "clientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_bb320dd25860311e9c8135c25ec" FOREIGN KEY ("pedido_id") REFERENCES "pedidos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_07ac3afe59c84077e5968bd6f63" FOREIGN KEY ("comprobante_id") REFERENCES "comprobantes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_a5ef18f1e91c2709fb99dd03d5a" FOREIGN KEY ("caja_id") REFERENCES "cajas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ventas" ADD CONSTRAINT "FK_5c564fe8d2b5182a37211405827" FOREIGN KEY ("usuario_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_5c564fe8d2b5182a37211405827"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_a5ef18f1e91c2709fb99dd03d5a"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_07ac3afe59c84077e5968bd6f63"`);
        await queryRunner.query(`ALTER TABLE "ventas" DROP CONSTRAINT "FK_bb320dd25860311e9c8135c25ec"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_2fc639de84f845569ac2c9f78aa"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_44db92bd8242455d454c1d2c5d9"`);
        await queryRunner.query(`ALTER TABLE "pedidos" DROP CONSTRAINT "FK_ed48ccf11914571bc1c845e592d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_51836035a0f08079451d537b245"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_685cb01ac5c88b5abb6bbe8aa60"`);
        await queryRunner.query(`ALTER TABLE "cajas" DROP CONSTRAINT "FK_6f28154a3dda0d70c72867f7c97"`);
        await queryRunner.query(`ALTER TABLE "cajas" DROP CONSTRAINT "FK_64f074ffa88f2ad899dc9b1448d"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_2784134d13bb90b049a95b54274"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_5b52af61814a34be3ab6c162165"`);
        await queryRunner.query(`ALTER TABLE "comprobantes" DROP CONSTRAINT "FK_52efe547ddd86fa9592a8ab3dfe"`);
        await queryRunner.query(`ALTER TABLE "detalle_comprobantes" DROP CONSTRAINT "FK_1f8632e49bb51f6a35a52815fe7"`);
        await queryRunner.query(`ALTER TABLE "detalle_comprobantes" DROP CONSTRAINT "FK_ca7830e72f5b176b12ecee07f35"`);
        await queryRunner.query(`ALTER TABLE "productos" DROP CONSTRAINT "FK_5aaee6054b643e7c778477193a3"`);
        await queryRunner.query(`ALTER TABLE "predicciones_demanda" DROP CONSTRAINT "FK_20a62f3a5ad61372f7b770c136a"`);
        await queryRunner.query(`ALTER TABLE "predicciones_demanda" DROP CONSTRAINT "FK_8aa30ebfbdd26c5096fff5fff4c"`);
        await queryRunner.query(`ALTER TABLE "facturas_proveedores" DROP CONSTRAINT "FK_16241fcacd3ab133d9a07abbfc4"`);
        await queryRunner.query(`ALTER TABLE "detalle_facturas_proveedores" DROP CONSTRAINT "FK_70bf44521a938647bcb03662af7"`);
        await queryRunner.query(`ALTER TABLE "detalle_facturas_proveedores" DROP CONSTRAINT "FK_8647aa38fa76368ef98e78c1cf8"`);
        await queryRunner.query(`ALTER TABLE "detalle_pedidos" DROP CONSTRAINT "FK_095863249e22548b6cd85dae392"`);
        await queryRunner.query(`ALTER TABLE "detalle_pedidos" DROP CONSTRAINT "FK_2720cdda307d262cfe40a2fce30"`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" DROP CONSTRAINT "FK_5126a73f7a1f343a37907d9eca7"`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" DROP CONSTRAINT "FK_ecae228362b00d658c9e489cb56"`);
        await queryRunner.query(`ALTER TABLE "aperturas_caja" DROP CONSTRAINT "FK_65ef2d17b6bdf57e8d3be96f84f"`);
        await queryRunner.query(`ALTER TABLE "mesas" DROP CONSTRAINT "FK_4ae856e133b757170844b0600f1"`);
        await queryRunner.query(`DROP TABLE "ventas"`);
        await queryRunner.query(`DROP TYPE "public"."ventas_metodo_pago_enum"`);
        await queryRunner.query(`DROP TABLE "pedidos"`);
        await queryRunner.query(`DROP TYPE "public"."pedidos_estado_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_estado_enum"`);
        await queryRunner.query(`DROP TABLE "sedes"`);
        await queryRunner.query(`DROP TYPE "public"."sedes_estado_enum"`);
        await queryRunner.query(`DROP TABLE "cajas"`);
        await queryRunner.query(`DROP TYPE "public"."cajas_estado_enum"`);
        await queryRunner.query(`DROP TABLE "comprobantes"`);
        await queryRunner.query(`DROP TYPE "public"."comprobantes_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."comprobantes_tipo_comprobante_enum"`);
        await queryRunner.query(`DROP TABLE "detalle_comprobantes"`);
        await queryRunner.query(`DROP TABLE "productos"`);
        await queryRunner.query(`DROP TYPE "public"."productos_origen_enum"`);
        await queryRunner.query(`DROP TYPE "public"."productos_estado_enum"`);
        await queryRunner.query(`DROP TABLE "predicciones_demanda"`);
        await queryRunner.query(`DROP TYPE "public"."predicciones_demanda_hora_rango_enum"`);
        await queryRunner.query(`DROP TABLE "modelo_ia"`);
        await queryRunner.query(`DROP TYPE "public"."modelo_ia_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."modelo_ia_tipo_enum"`);
        await queryRunner.query(`DROP TABLE "facturas_proveedores"`);
        await queryRunner.query(`DROP TYPE "public"."facturas_proveedores_estado_enum"`);
        await queryRunner.query(`DROP TYPE "public"."facturas_proveedores_procesado_por_ia_enum"`);
        await queryRunner.query(`DROP TABLE "detalle_facturas_proveedores"`);
        await queryRunner.query(`DROP TABLE "detalle_pedidos"`);
        await queryRunner.query(`DROP TABLE "categorias"`);
        await queryRunner.query(`DROP TABLE "clientes"`);
        await queryRunner.query(`DROP TYPE "public"."clientes_tipo_documento_enum"`);
        await queryRunner.query(`DROP TABLE "aperturas_caja"`);
        await queryRunner.query(`DROP TABLE "mesas"`);
        await queryRunner.query(`DROP TYPE "public"."mesas_estado_enum"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
